variable "sub_cluster_name" {
  type        = string
  description = "Name to use for the module sub-cluster"
  default     = "fact"
}

variable "node_count" {
  type        = number
  description = "Number of Virtual Machine nodes to provision"
  default     = 1
}

variable "admin_username" {
  type        = string
  description = "Admin user"
  default     = "admin_admin"
}

variable "resource_group_name" {
  description = "Resource group Name"
}

variable "location" {
  description = "Asset location"
}

variable "parent_vnetwork_name" {
  type        = string
  description = "Name of the virtual network this subnet will live under"
}

variable "parent_subnet_id" {
  type        = string
  description = "ID of the parent subnet"
}

variable "environment" {
  type        = string
  description = "Current Environment to provision within"
}

variable "default_tags" {
  type        = map(string)
  description = "Collection of default tags to apply to all resources"
}

variable "consul_server" {
  type        = string
  description = "IP address of a Consul server to join"
}

variable "vm_ssh_pubkey" {
  description = "Input for SSH Public Key"
  default     = "AUTOGENERATED"
}
